ci to run docker

diff --git a/.github/workflows/linter.yml b/.github/workflows/linter.yml
--- a/.github/workflows/linter.yml
+++ b/.github/workflows/linter.yml
@@ -1,4 +1,4 @@
-name: Flake 8 and Black
+name: Flake 8 and Test
 
 on:
   # Triggers the workflow on push or pull request events but only for the main branch
@@ -6,7 +6,6 @@ on:
   workflow_dispatch:
   pull_request:
     branches: [ main ]
-
 
 jobs:
   flake8-lint:
@@ -18,3 +17,31 @@ jobs:
         select: E402,E265,F841,F541,702
         maxlinelength: 120
         repotoken: ${{ secrets.GITHUB_TOKEN }}
+  
+  build_test:
+    runs-on: ubuntu-latest
+    steps:
+    - uses: actions/checkout@v2
+    - name: Branch name
+      run: echo running on branch ${GITHUB_REF##*/}
+    - name: Build Docker for DS Test
+      env:
+        PAT: ${{ secrets.JENKINS_BUILD_TOKEN }}
+      run: |
+        set -e
+        pwd
+        ls -l 
+        sudo chmod 666 /var/run/docker.sock
+        docker build --build-arg git_personal_token=$PAT --build-arg branch=${GITHUB_REF##*/} -t sail/datascience-test -f sail-safe-functions-test/docker/Dockerfile .
+        docker run sail/datascience-test
+  
+  workflow-conclusion:
+    # Without this step workflow remains "green" if build does fail.
+    if: always()
+    runs-on: ubuntu-latest
+    needs: [flake8-lint, build_test]
+    steps:
+      - uses: technote-space/workflow-conclusion-action@v2
+      - name: Check Job Status status and fail if they are red
+        if: env.WORKFLOW_CONCLUSION == 'failure'
+        run: exit 1
